version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports: ["6333:6333", "6334:6334"]
    volumes:
      - qdrant_storage:/qdrant/storage

  ingestor:
    build: ./services/ingestor
    container_name: ingestor
    environment:
      - PROGRAM_URL_AI=https://abit.itmo.ru/program/master/ai
      - PROGRAM_URL_AIPROD=https://abit.itmo.ru/program/master/ai_product
      - DATA_DIR=/app/data
      - QDRANT_URL=http://qdrant:6333
      - COLLECTION_NAME=itmo_mai
    volumes:
      - ./data:/app/data
    depends_on: [qdrant]
    # однократный прогон при старте: скачивание PDF + индексация
    command: ["python", "run.py"]

  api:
    build: ./services/api
    container_name: api
    environment:
      - QDRANT_URL=http://qdrant:6333
      - COLLECTION_NAME=itmo_mai
      - MODEL_QWEN=Qwen/Qwen3-1.7B
      - HF_HOME=/cache/hf
      - TORCH_USE_CUDA_DSA=0
    volumes:
      - ./data:/app/data
      - hf_cache:/cache/hf
    ports: ["8000:8000"]
    depends_on: [qdrant]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]   # если есть NVIDIA

  bot:
    build: ./services/bot
    container_name: bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - API_BASE=http://api:8000
    depends_on: [api]

volumes:
  qdrant_storage:
  hf_cache:
